### PR TITLE
New climate DLL for LANDIS-II v8

### PR DESCRIPTION
**Pull request by mslucash**
DLL for climate library v5

### CODE REVIEW

**Comment by rmscheller** [comment]
Melissa, could you rename to Library-Climate-v5.dll?  It makes updating extensions between major versions much easier, so long as you update the internal version number (in the csproj file).  Thanks!

**Comment by rmscheller** [comment]
Apologies, that was super unclear.  Landis.Library.Climate-v5.dll

**Comment by mslucash** [comment]
But the DLL looks correct to me.

Melissa

Melissa Lucash
Research Assistant Professor
Department of Geography
University of Oregon

http://melissalucash.com
________________________________

**Comment by rmscheller** [comment]
It has the 5.0.dll designation.  If we don't include the secondary versioning (.0) then updates are seamless, up until there's a -v6.dll

**Pull request merged**
